spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${profile}
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  web:
    locale: ko_KR
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.cache: DEBUG

management:
  endpoints:
    web:
      base-path: /health_check

kopis:
  performance:
    batch-count: 200
    url: http://www.kopis.or.kr/openApi/restful
  api:
    key: ${KOPIS_API_KEY}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

fcm:
  service-account-file: key/heyapplication-40e61-firebase-adminsdk-cd5mk-6b4dd26836.json
  project-id: heyapplication-40e61

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://ec2-3-39-168-47.ap-northeast-2.compute.amazonaws.com:5432/hey
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  task:
    execution:
      pool:
        core-size: 10
server:
  port: 8180
logging:
  level:
    root: info
    org.springframework.web: debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: off

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://ec2-3-39-168-47.ap-northeast-2.compute.amazonaws.com:5432/hey
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true


  data:
    redis:
      host: localhost
      port: 6379
  task:
    execution:
      pool:
        core-size: 2
server:
  port: 8190
logging:
  level:
    root: info
    org.springframework.web: debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: off

---
#spring.config.active.on-profile: prod
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hey
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#
#  data:
#    redis:
#      host: redis
#      port: 6379
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect